// How to request data from an API using javascript and jQuery ...

// There are many ways to do this! EX: ...
// 1. jQuerys $.ajax() function ...
// 2. The Browsers fetch() function ...
// 3. Using the Axios http client library ...

const url = 'http://www.omdbapi.com/?apikey=c3ff07d0&t=Die+Hard';

$.ajax(url).then(function(data) {
    console.log('Movie data is ready')
    console.log(data)
}), function() {
    console.log('Something is wrong')
    console.log(error)    // This is error handling
}